version: '3.2'
services:
  redis:
    image: 'redis:7.0.7-alpine'
    command: redis-server
    volumes:
      - ./redis:/data
    networks:
      - network
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: foreman start -p 13006
    user: '1001'
    cap_drop:
      - ALL
    #cap_add:
    env_file:
      - .env
    volumes:
      - ./src:/home/myuser/local/app
      #- type: tmpfs
      #  target: /home/myuser/local/app/tmp/pids/
      #- bundler_gems: /home/local/bundle/
    ports:
      - "13006:13006"
    networks:
      - network
#volumes:
  #bundler_gems:
networks:
  network: