version: '3.2'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: foreman start -p 3000
    env_file:
      - .env
    volumes:
      - ./src:/home/local/app
      - type: tmpfs???
        target: /home/local/app/tmp/pids/
      - bundler_gems: /home/local/bundle/
    ports:
      - "3000:3000"
    networks:
      - network
volumes:
  bundler_gems:
networks:
  network: