#use rails credentials:edit to manage name & password
#ref: https://dev.to/vvo/secrets-environment-variables-config-files-the-ruby-on-rails-case-433f
default: &default
  address: "smtp-relay@gmail.com"
  port: 587
  domain: "cmdm.csie.ntu.edu.tw"
  authentication: "plain"
  user_name: "fasteval_parkinsonism@cmdm.csie.ntu.edu.tw"
  password: "*ejZCYS&KqrAJ4gK*"
  enable_starttls_auto: true
development:
  <<: *default

production:
  <<: *default