development:
  address: "smtp-relay.gmail.com"
  port: 587
  domain: "cmdm.csie.ntu.edu.tw"
  authentication: "plain"
  user_name: "fasteval_parkinsonism@cmdm.csie.ntu.edu.tw" 
  password: "<account pwd>"
  enable_starttls_auto: true
production:
  address: "smtp-relay.gmail.com"
  port: 587
  domain: "cmdm.csie.ntu.edu.tw"
  authentication: "plain"
  user_name: "fasteval_parkinsonism@cmdm.csie.ntu.edu.tw" 
  password: "<account pwd>"
  enable_starttls_auto: true
