development:
  address: "smtp.sendgrid.net"
  port: 587
  domain: "lab@cmdm.csie.ntu.edu.tw"
  authentication: "plain"
  user_name: "apikey" # This is the string literal 'apikey', NOT the ID of your API key
  password: "<SENDGRID_API_KEY>" # This is the secret sendgrid API key which was issued during API key creation
  enable_starttls_auto: true
production:
  address: "smtp.sendgrid.net"
  port: 587
  domain: "lab@cmdm.csie.ntu.edu.tw"
  authentication: "plain"
  user_name: "apikey"
  password: "<SENDGRID_API_KEY>"
  enable_starttls_auto: true
