#use rails credentials:edit to manage name & password
#ref: https://dev.to/vvo/secrets-environment-variables-config-files-the-ruby-on-rails-case-433f
default: &default
  address: "<%= Rails.application.credentials.email[:address] %>"
  port: 587
  domain: "<%= Rails.application.credentials.email[:domain] %>"
  authentication: "plain"
  user_name: "<%= Rails.application.credentials.email[:user_name] %>"
  password: "<%= Rails.application.credentials.email[:password] %>"
  enable_starttls_auto: true
development:
  <<: *default

production:
  <<: *default