development:
  address: "<%= ENV.fetch("EMAIL_SMTP") %>"
  port: 587
  domain: "<%= ENV.fetch("EMAIL_DOMAIN") %>"
  authentication: "plain"
  user_name: "<%= ENV.fetch("EMAIL_ADDR") %>" 
  password: "<%= ENV.fetch("EMAIL_PASSWD") %>"
  enable_starttls_auto: true
production:
  address: "<%= ENV.fetch("EMAIL_SMTP") %>"
  port: 587
  domain: "<%= ENV.fetch("EMAIL_DOMAIN") %>"
  authentication: "plain"
  user_name: "<%= ENV.fetch("EMAIL_ADDR") %>" 
  password: "<%= ENV.fetch("EMAIL_PASSWD") %>"
  enable_starttls_auto: true
